/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Data_MapPoint" CASCADE;

CREATE TABLE "Data_MapPoint" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "mpid" BIGINT NOT NULL,
  "pose" TEXT NOT NULL,
  "data" TEXT NOT NULL);

