/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Data_KeyFrame" CASCADE;

CREATE TABLE "Data_KeyFrame" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "kfid" BIGINT NOT NULL,
  "pose" TEXT NOT NULL,
  "data" TEXT NOT NULL);

